### PR TITLE
fix(STADTPULS-517): Reduce humungous docs text size

### PR DESCRIPTION
**Pull request by vogelino**
This PR reduces the overall text size of the docs on larger screens.

### CODE REVIEW

**Comment by Esshahn** [comment]
while it isn't huge anymore, I personally would prefer to have the text a bit smaller even.

**Comment by vogelino** [comment]
> while it isn't huge anymore, I personally would prefer to have the text a bit smaller even.

I made it even smaller

**Review by dnsos — APPROVED** [review]
Nice, I like that size.

**Comment by Esshahn** [comment]
cool

**Pull request merged**
