### PR TITLE
Feat/196 makers documentation

### PR DESCRIPTION
**Pull request by julizet**
I added some new pages to the overall documentation section of stadtpuls. Such as:
- add new project 
- add new device
- config TTN application

I updated pages such as:
- register for an account
- faq

Additionally, I fixed some typos and slightly changed the wording in some pages. 

Pages missing:
- view data
- troubleshooting

Looking forward to your thoughts and feedback :)

### CODE REVIEW

**Review by vogelino — APPROVED** [review]
Amazing thank you very much! Love it! 😍  I see you used a warning sign a few times. We might want to build a component for that in that vibe at one point:

Screen Shot 2021-09-06 at 10 09 10 AM

**Comment by Esshahn** [comment]
LGTM - I fixed some minor wordings and typos.

**Comment by julizet** [comment]
> LGTM - I fixed some minor wordings and typos.

thank you for double checking

**Comment by julizet** [comment]
> Amazing thank you very much! Love it! 😍 I see you used a warning sign a few times. We might want to build a component for that in that vibe at one point:
> 
> Screen Shot 2021-09-06 at 10 09 10 AM

Like the idea! :) think we could need this little component here and then withing the future documentation. But would keep it a little more simple that what you just screenshotted

**Comment by julizet** [comment]
@ff6347 I am still working on this branch to add all doc pages --> see Slack

**Comment by ff6347** [comment]
@julizet Okay sorry. Since you merged that branch I thought we could delete it. 
I would prefer not to merge it in the first place or to create a new branch based on main if you already merged it. Since keeping merged branches around can create confusion. Quod erat demonstrandum

**Pull request merged**
