### PR TITLE
Feat/documentation

### PR DESCRIPTION
**Pull request by julizet**
this PR includes:
- new structure of sidemenu
  - thus, removes 404 error
- updated ttn documentation 
  - thus, uses api/v3
  - thus, added payload formatter and payload packaging

### CODE REVIEW

**Comment by julizet** [comment]
the `http-sensor.mdx` document is still work in progress. However, due to another project and limited working hours, ymy capacities for this weeks are already depleted. 

It would be nice if our API pros (@ff6347 or @vogelino) can finish the http integration documentation

**Comment by vogelino** [comment]
> It would be nice if our API pros (@ff6347 or @vogelino) can finish the http integration documentation

Sure thing! Thx for the docs update!

**Comment by ff6347** [comment]
I'll take a look into http docs now

**Comment by Esshahn** [comment]
@ff6347 can add Helligkeit on the welcome page?

Temperatur
CO2
Luftfeuchtigkeit
Druck
Helligkeit
Lautstärke
Einheitenzähler

**Pull request closed without merging**
