### PR TITLE
STADTPULS-725 ci(semver release): Adds config, packages & action

### PR DESCRIPTION
**Pull request by ff6347**
This should enable semantic release bot to run on a github aciton and
- add a changelog
- bump the package version
- commit all those things
- create a github release from it

### CODE REVIEW

**Review by vogelino — DISMISSED** [review]
Great addition! 🚀

**Comment by ff6347** [comment]
>   Error: fatal: No url found for submodule path 'supabase' in .gitmodules

This looks like the supabase test Setup slipped into the git history. 😔

**Comment by vogelino** [comment]
> > Error: fatal: No url found for submodule path 'supabase' in .gitmodules
> 
> This looks like the supabase test Setup slipped into the git history. 😔

Damn! I will remove it illico presto

**Review by vogelino — APPROVED** [review]
Now everything seems to work out fine. 👍

**Pull request merged**
