### PR TITLE
Staging to production (Including the new Sensors Map)

### PR DESCRIPTION
**Pull request by vogelino**
This PR merges the changes made since last deployment including the Sensors Map.

### CODE REVIEW

**Comment by dnsos** [comment]
Tested (macOS, latest Firefox):

**work in progress**

- [x] sign in
- [x] create new sensor
- [x] sensor is displayed in map view
- [x] edit sensor
- [x] post records to new sensor (via HTTP)
- [ ] delete sensor
- [ ] sensor has disappeared from map view
- [ ] sign up
- [ ] edit profile

**Review by dnsos — DISMISSED** [review]
On `/sensors` (macOS, Firefox) the map navigation icons are not visible. Also it seems that the Mapbox attribution is hidden at the bottom of the map.

Screenshot 2022-02-22 at 11 58 02

**Comment by vogelino** [comment]
> On `/sensors` (macOS, Firefox) the map navigation icons are not visible. Also it seems that the Mapbox attribution is hidden at the bottom of the map.
> 
> Screenshot 2022-02-22 at 11 58 02

This is a caching issue. A (hard) reload should fix it. 👍

**Comment by dnsos** [comment]
> > On `/sensors` (macOS, Firefox) the map navigation icons are not visible. Also it seems that the Mapbox attribution is hidden at the bottom of the map.
> 
> This is a caching issue. A (hard) reload should fix it. 👍

True! Thanks for the hint

**Review by dnsos — APPROVED** [review]

**Pull request merged**
