### PR TITLE
feat(STADTPULS-488): sort and paginate accounts overview

### PR DESCRIPTION
**Pull request by dnsos**
This PR turned out a a bit differently than originally planned. STADTPULS-489 is outdated, instead we handle the accounts overview as discussed in the comments below.

### CODE REVIEW

**Review by vogelino — COMMENTED** [review]
Didn't we decide to put the accounts at the end of the list? Also, this solution is client-side. If we plan to add pagination this sorting won't work for long. We might rather do the sorting on the server-side. There is possibly a way to do this with supabase's `order` function right?

**Comment by dnsos** [comment]
> Didn't we decide to put the accounts at the end of the list?
My understanding was that we would do that not for the accounts but for the sensors that don't have any records yet. But perhaps I'm wrong. @Esshahn, can you help out?

**Comment by dnsos** [comment]
> If we plan to add pagination this sorting won't work for long.

Good point, thanks for the reminder. Maybe it makes sense to solve the pagination together with this

**Comment by vogelino** [comment]
I think not showing accounts that exist is not so good. Making meaningful accounts easier to spot better. Rewarding instead of punishing. 🎖️

**Comment by dnsos** [comment]
@vogelino or @Esshahn, please check again after the latest commits. I have now used this PR to actually implement the sorting and pagination of the accounts overview (same behaviour as the sensors overview).

**Review by vogelino — APPROVED** [review]
This is great! Thx for implementing!

**Pull request merged**
