### PR TITLE
Fix/records limit in account

### PR DESCRIPTION
**Pull request by dnsos**
This PR adds a limit to the records that are fetched when the user's sensors are fetched. In the refactoring yesterday, the limit got lost. Here it is reintroduced.

This fixes the problem that `getAccountDataByUsername` fetches records without limit and thus breaks the `accounts/[username]` route where the function is called and the user has too many records (e.g. 280.000).

### CODE REVIEW

**Comment by ff6347** [comment]
Why do we fetch records at all when we want the sensors? If we cap it it makes no sense.

**Comment by ff6347** [comment]
Agghhhhhhh. The chart on the card …

**Review by ff6347 — APPROVED** [review]
LGTM

**Review by vogelino — APPROVED** [review]
👍

**Pull request merged**
